579c48e211ae952530ffc8738709f078d5dd215e:
  name: Mario Kart 64 [US]
  path: yamls/us
  config:
    gbi: F3DEX_MK64
    sort: OFFSET
    enums: 
      - include/defines.h
    output:
      binary: mkcube.otr
      headers: include/assets
      code: assets/code
  metadata: [yamls/courses]
  segments:
    - 0x000000
    - 0x000000
    - 0x12AAE0
    - 0x000000
    - 0x000000
    - 0x000000
    - 0x825800
    - 0x000000
    - 0x000000
    - 0x88CD70
    - 0x729A30
    - 0x821D10
    - 0x7FA3C0
    - 0x132B50
    - 0x000000
    - 0x145470
