# Optional configuration file for import.py. Put it in the root or in tools/
# of the repo you are importing from.

compiler_type = "ido"

[decompme.compilers]
"tools/ido-recomp/linux/cc" = "ido5.3"

[preserve_macros]
"gs?DP.*" = "void"
"gs?SP.*" = "void"
"G_.*" = "int"
"VIRTUAL_.*" = "unsigned int"
"PHYSICAL_.*" = "unsigned int"
"TIME_TRIAL_.*" = "int"
"TEXT_.*" = "int"
"OS_.*" = "int"
"SEGMENT_.*" = "int"
"ACTOR_.*" = "int"
"A_[A-Z]+" = "int"
"a[A-Za-z]+" = "void"
"_SHIFT[LR]" = "void"
"ALIGN.*" = "int"
"aClearBuffer" = "void"
"aEnvSetup1Alt" = "void"
"aEnvSetup1" = "void"
"aEnvSetup2" = "void"
"aEnvMixer" = "void"
