name: Linux Compile test

on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Get Complementary file
        uses: actions/checkout@v4
        with:
          path: complementary_file
          repository: UnspaghettifyKart/action-build-private-file
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: |
          sudo apt install build-essential cmake pkg-config git binutils-mips-linux-gnu python3 zlib1g-dev libaudiofile-dev libcapstone-dev
      - name: Build
        run: |
          cp -r complementary_file/* .
          make assets -j
          make -j
